# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Guardian Apply'
description: |-
  Use this action to run a Terraform Apply process for merged pull requests.
inputs:
  working_directory:
    description: 'The working directory for Guardian to execute commands in.'
    required: false
    default: '.'
  bucket_name:
    description: 'The Google Cloud Storage bucket name to retrieve Guardian plan files (e.g. my-guardian-state-bucket).'
    required: true
  terraform_version:
    description: 'The Terraform version for Guardian to use.'
    required: true
  protect_lockfile:
    description: 'Enable lockfile protection to prevent modification of the Terraform lockfile.'
    required: false
    default: 'true'
  lock_timeout:
    description: 'The duration Terraform should wait to obtain a lock when running commands that modify state.'
    required: false
    default: '10m'
  max_retries:
    description: 'The maxiumum number of retries when handling failures.'
    required: false
    default: '5'
  max_retry_delay:
    description: 'The max retry delay in seconds when handling failures.'
    required: false
    default: '60'
outputs:
  has-diff:
    description: 'Returns "true" if the Terraform plan file has a diff'
    value: '${{ steps.has-diff.outputs.result }}'
runs:
  using: 'composite'
  steps:
    - name: 'Bootstrap Out File'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        echo "Unknown error, see logs for details." > $OUT_FILENAME
    - name: 'Validate Run Number'
      if: '${{ github.run_attempt > 1 }}'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        MSG="Guardian Apply workflow re-run attempted. Guardian Apply workflows cannot be re-run. To run apply again, create another Pull Request or contact a repo admin."
        echo "$MSG" > $OUT_FILENAME
        echo "::error ::$MSG"
        exit 1
    # must come first to ensure these exist to delete plan file on errors
    - name: 'Setup Node'
      uses: 'actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d' # ratchet:actions/setup-node@v3
      with:
        node-version: '16'
    - name: 'Install Google Cloud Storage SDK'
      shell: 'bash'
      run: |-
        npm install @google-cloud/storage@~6.9.5
    - name: 'Validate Event'
      if: '${{ github.event_name != ''push'' }}'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        MSG="Configuration error, Guardian Apply can only be run for 'push' events."
        echo "$MSG" > $OUT_FILENAME
        echo "::error ::$MSG"
        exit 1
    - name: 'Get PR Number'
      id: 'get-pr'
      uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
      with:
        github-token: '${{ github.token }}'
        retries: '${{ inputs.max_retries }}'
        script: |-
          const { data: pullRequests } =
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: process.env.GITHUB_SHA,
            });

          const pullRequest = pullRequests.find((pr) => pr.state === "closed");
          if (!pullRequest) {
            core.setFailed(
              `Failed to get pull request for merged SHA: ${process.env.GITHUB_SHA}`
            );
            process.exit(1);
          }

          return pullRequest.number;
    - name: 'Determine Plan Diff'
      id: 'has-diff'
      uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
      env:
        OUT_FILEPATH: '${{ inputs.working_directory }}/out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        GUARDIAN_PLAN_PREFIX: 'guardian-plans/${{ github.repository }}/${{ steps.get-pr.outputs.result }}/${{ inputs.working_directory }}'
        BUCKET_NAME: '${{ inputs.bucket_name }}'
        WORKING_DIRECTORY: '${{ inputs.working_directory }}'
        MAX_RETRIES: '${{ inputs.max_retries }}'
        MAX_RETRY_DELAY: '${{ inputs.max_retry_delay }}'
      with:
        result-encoding: 'string'
        script: |-
          const fs = require("fs");
          const { EOL } = require("os");

          try {
            const { Storage, IdempotencyStrategy } = require("@google-cloud/storage");
            const bucketName = process.env.BUCKET_NAME;
            const fileName = `${process.env.GUARDIAN_PLAN_PREFIX}/tfplan.binary`;
            const destFileName = `${process.env.WORKING_DIRECTORY}/tfplan.binary`;

            const storage = new Storage({
              retryOptions: {
                autoRetry: true,
                retryDelayMultiplier: 3,
                totalTimeout: 500,
                maxRetryDelay: process.env.MAX_RETRY_DELAY,
                maxRetries: process.env.MAX_RETRIES,
                idempotencyStrategy: IdempotencyStrategy.RetryAlways,
              },
            });

            const [metadata] = await storage
              .bucket(bucketName)
              .file(fileName)
              .getMetadata();

            if(metadata && metadata.metadata && metadata.metadata["plan_exit_code"] === "0"){
              core.info("Plan has no diff. Skipping...")
              return "false"
            }

            return "true"
          } catch (err) {
            const errString = JSON.stringify(err, undefined, 2);
            const errorData = `# Determine Plan Diff${EOL}Error: ${errString}`;

            fs.writeFileSync(process.env.OUT_FILEPATH, errorData, { encoding: "utf8" });

            core.error("Failed to determine plan diff");
            core.error(errString);
            core.setFailed("Failed to determine plan diff.");
          }
    - name: 'Start Comment'
      id: 'comment'
      if: '${{ steps.has-diff.outputs.result == ''true'' }}'
      uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
      env:
        WORKING_DIRECTORY: '${{ inputs.working_directory }}'
        PR_NUMBER: '${{ steps.get-pr.outputs.result }}'
      with:
        github-token: '${{ github.token }}'
        retries: '${{ inputs.max_retries }}'
        script: |-
          const { data: prComment } = await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: process.env.PR_NUMBER,
            body: `**\`🔱 Guardian 🔱 APPLY\`** - 🟨 Running for dir: \`${process.env.WORKING_DIRECTORY}\` [[logs](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}/attempts/${process.env.GITHUB_RUN_ATTEMPT})]`,
          });

          return prComment.id;

    - name: 'Setup Terraform'
      if: '${{ steps.has-diff.outputs.result == ''true'' }}'
      uses: 'abcxyz/secure-setup-terraform@2912e6e8b49e9b5de6583825482889dccac4f3dc' # ratchet:abcxyz/secure-setup-terraform@main
      with:
        terraform_version: '${{ inputs.terraform_version }}'
        terraform_module_location: './${{ inputs.working_directory }}'
        terraform_lockfile_location: './${{ inputs.working_directory }}'
        protect_lockfile: '${{ inputs.protect_lockfile }}'
        terraform_wrapper: false
    - name: 'Terraform Init'
      if: '${{ steps.has-diff.outputs.result == ''true'' }}'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        TF_IN_AUTOMATION: 'true' # tell terraform this is an automated workflow https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
      run: |-
        echo "# Terraform Init" > $OUT_FILENAME
        terraform init -input=false -no-color 2>&1 | tee -a $OUT_FILENAME
    - name: 'Download Plan File'
      if: '${{ steps.has-diff.outputs.result == ''true'' }}'
      uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
      env:
        OUT_FILEPATH: '${{ inputs.working_directory }}/out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        GUARDIAN_PLAN_PREFIX: 'guardian-plans/${{ github.repository }}/${{ steps.get-pr.outputs.result }}/${{ inputs.working_directory }}'
        BUCKET_NAME: '${{ inputs.bucket_name }}'
        WORKING_DIRECTORY: '${{ inputs.working_directory }}'
        MAX_RETRIES: '${{ inputs.max_retries }}'
        MAX_RETRY_DELAY: '${{ inputs.max_retry_delay }}'
      with:
        script: |-
          const fs = require("fs");
          const { EOL } = require("os");

          try {
            const { Storage, IdempotencyStrategy } = require("@google-cloud/storage");
            const bucketName = process.env.BUCKET_NAME;
            const fileName = `${process.env.GUARDIAN_PLAN_PREFIX}/tfplan.binary`;
            const destFileName = `${process.env.WORKING_DIRECTORY}/tfplan.binary`;

            const storage = new Storage({
              retryOptions: {
                autoRetry: true,
                retryDelayMultiplier: 3,
                totalTimeout: 500,
                maxRetryDelay: process.env.MAX_RETRY_DELAY,
                maxRetries: process.env.MAX_RETRIES,
                idempotencyStrategy: IdempotencyStrategy.RetryAlways,
              },
            });

            await storage
              .bucket(bucketName)
              .file(fileName)
              .download({ destination: destFileName });
          } catch (err) {
            const errString = JSON.stringify(err, undefined, 2);
            const errorData = `# Download Plan File${EOL}Error: ${errString}`;

            fs.writeFileSync(process.env.OUT_FILEPATH, errorData, { encoding: "utf8" });

            core.error("Failed to download plan file");
            core.error(errString);
            core.setFailed("Failed to download plan file.");
          }
    - name: 'Terraform Apply'
      if: '${{ steps.has-diff.outputs.result == ''true'' }}'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        TF_IN_AUTOMATION: 'true' # tell terraform this is an automated workflow https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
        LOCK_TIMEOUT: '${{ inputs.lock_timeout }}'
      run: |-
        echo "# Terraform Apply" > $OUT_FILENAME
        terraform apply -lock-timeout=$LOCK_TIMEOUT -input=false -no-color tfplan.binary 2>&1 | tee -a $OUT_FILENAME
    - name: 'GitHub Format'
      if: '${{ steps.has-diff.outputs.result == ''true'' }}'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        sed -i -E 's|^([[:space:]]*)([~])|\1\!|g' $OUT_FILENAME
        sed -i -E 's|^([[:space:]]*)([-+\!])|\2\1|g' $OUT_FILENAME
    - name: 'Create Success File'
      if: '${{ steps.has-diff.outputs.result == ''true'' }}'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        SUCCESS_FILENAME: 'success_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        cp $OUT_FILENAME $SUCCESS_FILENAME

        # Since the delete plan action always runs, we should clear the outfile.
        # If the delete plan action fails, it can append to empty file and not to successful output.
        rm $OUT_FILENAME
    - name: 'Delete Plan File'
      if: '${{ steps.get-pr.outcome == ''success'' && always() }}'
      uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
      env:
        OUT_FILEPATH: '${{ inputs.working_directory }}/out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        GUARDIAN_PLAN_PREFIX: 'guardian-plans/${{ github.repository }}/${{ steps.get-pr.outputs.result }}/${{ inputs.working_directory }}'
        BUCKET_NAME: '${{ inputs.bucket_name }}'
        MAX_RETRIES: '${{ inputs.max_retries }}'
        MAX_RETRY_DELAY: '${{ inputs.max_retry_delay }}'
      with:
        script: |-
          const fs = require("fs");
          const { EOL } = require("os");

          try {
            const { Storage, IdempotencyStrategy } = require("@google-cloud/storage");
            const bucketName = process.env.BUCKET_NAME;
            const fileName = `${process.env.GUARDIAN_PLAN_PREFIX}/tfplan.binary`;

            const storage = new Storage({
              retryOptions: {
                autoRetry: true,
                retryDelayMultiplier: 3,
                totalTimeout: 500,
                maxRetryDelay: process.env.MAX_RETRY_DELAY,
                maxRetries: process.env.MAX_RETRIES,
                idempotencyStrategy: IdempotencyStrategy.RetryAlways,
              },
            });

            await storage
              .bucket(bucketName)
              .file(fileName)
              .delete({ ignoreNotFound: true });
          } catch (err) {
            const errString = JSON.stringify(err, undefined, 2);
            const errorData = `${EOL}${EOL}# Delete Plan File${EOL}Error: ${errString}`;

            // Append here since this always runs, regardless of previous failures
            fs.appendFileSync(process.env.OUT_FILEPATH, errorData, { encoding: "utf8" });

            core.error("Failed to delete plan file");
            core.error(errString);
            core.setFailed("Failed to delete plan file.");
          }
    # Precaution to ensure outfile exists to prevent unneccessary i/o errors
    - name: 'Ensure Outfile'
      if: '${{ failure() }}'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        touch $OUT_FILENAME
    - name: 'Failure Comment'
      if: '${{ steps.get-pr.outcome == ''success'' && failure() }}'
      uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
      env:
        COMMENT_ID: '${{ steps.comment.outputs.result }}'
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        WORKING_DIRECTORY: '${{ inputs.working_directory }}'
      with:
        github-token: '${{ github.token }}'
        retries: '${{ inputs.max_retries }}'
        script: |-
          const fs = require("fs");
          const msg = fs.readFileSync(
            `${process.env.WORKING_DIRECTORY}/${process.env.OUT_FILENAME}`,
            { encoding: "utf8" }
          );

          await github.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: process.env.COMMENT_ID,
            body: `**\`🔱 Guardian 🔱 APPLY\`** - 🟥 Failed for dir: \`${process.env.WORKING_DIRECTORY}\` [[logs](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}/attempts/${process.env.GITHUB_RUN_ATTEMPT})]\n
          <details>
          <summary>Details</summary>\n
          \`\`\`diff\n
          ${msg}
          \`\`\`
          </details>`,
          });

    - name: 'Success Comment'
      if: '${{ steps.get-pr.outcome == ''success'' && steps.has-diff.outputs.result == ''true'' && success() }}'
      uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
      env:
        COMMENT_ID: '${{ steps.comment.outputs.result }}'
        SUCCESS_FILENAME: 'success_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        WORKING_DIRECTORY: '${{ inputs.working_directory }}'
      with:
        github-token: '${{ github.token }}'
        retries: '${{ inputs.max_retries }}'
        script: |-
          const fs = require("fs");
          const msg = fs.readFileSync(
            `${process.env.WORKING_DIRECTORY}/${process.env.SUCCESS_FILENAME}`,
            { encoding: "utf8" }
          );

          await github.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: process.env.COMMENT_ID,
            body: `**\`🔱 Guardian 🔱 APPLY\`** - 🟩 Successful for dir: \`${process.env.WORKING_DIRECTORY}\` [[logs](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}/attempts/${process.env.GITHUB_RUN_ATTEMPT})]

          <details>
          <summary>Details</summary>\n
          \`\`\`diff\n
          ${msg}
          \`\`\`
          </details>`,
          });
