# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1beta3'
kind: 'Template'

desc: 'Generate the default set of Guardian workflows Terraform infrastructure repositories.'

inputs:
  - name: 'terraform_directory'
    desc: 'A sub-directory for all Terraform files'
    default: '.'
  - name: 'terraform_version'
    desc: 'The Terraform version to use'
  - name: 'tagrep_version'
    desc: 'The Tagrep version to use. See https://github.com/abcxyz/tagrep/releases'
  - name: 'guardian_wif_provider'
    desc: 'The Google Cloud workload identity federation provider for Guardian'
  - name: 'guardian_service_account'
    desc: 'The Google Cloud service account for Guardian'
    rules:
      - rule: 'gcp_matches_service_account(guardian_service_account)'
  - name: 'guardian_state_bucket'
    desc: 'The Google Cloud storage bucket for Guardian state'

steps:
  - desc: 'Include required files and directories'
    action: 'include'
    params:
      paths:
        - 'contents/workflows'
        - 'contents/policies/guardian_admin_workflow_permissions.rego'
      as:
        - '.github/workflows'
        - 'policy/guardian/admin/workflow_permissions.rego'

  - desc: 'Replace variables'
    action: 'string_replace'
    params:
      paths:
        - '.github/workflows'
      replacements:
        - to_replace: 'REPLACE_TERRAFORM_DIRECTORY'
          with: '{{.terraform_directory}}'
        - to_replace: 'REPLACE_TERRAFORM_VERSION'
          with: '{{.terraform_version}}'
        - to_replace: 'REPLACE_TAGREP_VERSION'
          with: '{{.tagrep_version}}'
        - to_replace: 'REPLACE_GUARDIAN_WIF_PROVIDER'
          with: '{{.guardian_wif_provider}}'
        - to_replace: 'REPLACE_GUARDIAN_WIF_SERVICE_ACCOUNT'
          with: '{{.guardian_service_account}}'
        - to_replace: 'REPLACE_GUARDIAN_STATE_BUCKET'
          with: '{{.guardian_state_bucket}}'
        - to_replace: 'REPLACE_GUARDIAN_VERSION_TAG'
          with: '{{ trimPrefix ._git_tag "v" }}'

  # TODO: once https://github.com/abcxyz/abc/pull/423 is available, switch to a rule requiring a '_git_tag' value
  - desc: 'Print warning if rendered without git tag'
    action: 'print'
    if: '_git_tag == ""'
    params:
      message: |-
        #
        # WARNING ##############################
        #
        # The template was rendered without a valid git tag. For best compatibility, we recommended
        # re-rendering this template using one of the latest tags at https://github.com/abcxyz/guardian/tags.
        #
        ########################################
