# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Guardian plan is used to run the Terraform plan commands for a set of
# directories after a pull request has been created.
name: 'guardian_plan'
run-name: 'guardian_plan - [PR #${{ github.event.pull_request.number }}]'

on:
  pull_request_target:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

# only one plan, per pr should run at a time
concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}-${{ github.head_ref || github.ref }}'

env:
  TERRAFORM_DIRECTORY: 'REPLACE_TERRAFORM_DIRECTORY'
  GUARDIAN_WIF_PROVIDER: 'REPLACE_GUARDIAN_WIF_PROVIDER'
  GUARDIAN_WIF_SERVICE_ACCOUNT: 'REPLACE_GUARDIAN_WIF_SERVICE_ACCOUNT'
  GUARDIAN_BUCKET_NAME: 'REPLACE_GUARDIAN_STATE_BUCKET'

jobs:
  init:
    runs-on: 'ubuntu-latest'
    outputs:
      directories: '${{ steps.dirs.outputs.directories }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0 # get everything so we can use git diff
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Guardian Directories'
        id: 'dirs'
        uses: 'abcxyz/guardian/.github/actions/directories@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/directories@main
        with:
          terraform_directory: '${{ env.TERRAFORM_DIRECTORY }}'
          detect_plan_changes: true

      - name: 'Guardian Remove Previous Plan Comments'
        uses: 'abcxyz/guardian/.github/actions/hide-plan-comments@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/hide-plan-comments@main
        with:
          strategy: 'delete'

  plan:
    if: |
      needs.init.outputs.directories != '[]'
    needs:
      - 'init'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        working_directory: '${{ fromJSON(needs.init.outputs.directories) }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ env.GUARDIAN_WIF_PROVIDER }}'
          service_account: '${{ env.GUARDIAN_WIF_SERVICE_ACCOUNT }}'

      - name: 'Guardian Plan'
        uses: 'abcxyz/guardian/.github/actions/plan@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/plan@main
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        with:
          working_directory: '${{ matrix.working_directory }}'
          bucket_name: '${{ env.GUARDIAN_BUCKET_NAME }}'
          terraform_version: 'REPLACE_TERRAFORM_VERSION'
          protect_lockfile: true

  plan_success:
    if: '${{ always() }}'
    runs-on: 'ubuntu-latest'
    needs:
      - 'init'
      - 'plan'
    steps:
      - name: 'Guardian Post Plan Status'
        uses: 'abcxyz/guardian/.github/actions/plan-status@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/plan-status@main
        with:
          init_result: '${{ needs.init.result }}'
          plan_result: '${{ needs.plan.result }}'
