# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Guardian fix is used to run Terraform commands that are most often used
# to fix state after a failed workflow or get outputs for a given module
# directory. Any user with write permissions on the repo can run this workflow.
name: 'guardian_run'
run-name: 'guardian_run - [${{ inputs.command }}] [${{ inputs.directories }}]'

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'COMMAND - The Terraform command to run.'
        required: true
        type: 'choice'
        default: 'plan'
        options:
          - 'plan'
          - 'apply'
          - 'output'
      directories:
        description: 'DIRECTORIES - A CSV list of directories execute the Terraform command in. If left blank, the Terraform command will run for all configured directories.'
        type: 'string'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'

# only one fix  should run at a time
concurrency:
  group: '${{ github.workflow }}'

env:
  TERRAFORM_DIRECTORY: 'REPLACE_TERRAFORM_DIRECTORY'
  GUARDIAN_WIF_PROVIDER: 'REPLACE_GUARDIAN_WIF_PROVIDER'
  GUARDIAN_WIF_SERVICE_ACCOUNT: 'REPLACE_GUARDIAN_WIF_SERVICE_ACCOUNT'

jobs:
  init:
    runs-on: 'ubuntu-latest'
    outputs:
      directories: '${{ steps.dirs.outputs.directories }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3

      - name: 'Guardian Directories'
        id: 'dirs'
        uses: 'abcxyz/guardian/.github/actions/directories@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/directories@main
        with:
          terraform_directory: '${{ env.TERRAFORM_DIRECTORY }}'
          directories: '${{ inputs.directories }}'

  admin:
    if: |
      needs.init.outputs.directories != '[]'
    needs:
      - 'init'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        working_directory: '${{ fromJSON(needs.init.outputs.directories) }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ env.GUARDIAN_WIF_PROVIDER}}'
          service_account: '${{ env.GUARDIAN_WIF_SERVICE_ACCOUNT }}'

      - name: 'Guardian Output'
        if: |
          inputs.command == 'output'
        uses: 'abcxyz/guardian/.github/actions/admin@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/admin@main
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        with:
          require_admin: 'false'
          command: 'output'
          terraform_init: 'true'
          working_directory: '${{ matrix.working_directory }}'
          terraform_version: 'REPLACE_TERRAFORM_VERSION'
          protect_lockfile: true

      - name: 'Guardian Plan'
        if: |
          inputs.command == 'plan'
        uses: 'abcxyz/guardian/.github/actions/admin@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/admin@main
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        with:
          require_admin: 'false'
          command: 'plan -input=false -lock-timeout=10m'
          terraform_init: 'true'
          working_directory: '${{ matrix.working_directory }}'
          terraform_version: 'REPLACE_TERRAFORM_VERSION'
          protect_lockfile: true

      - name: 'Guardian Apply'
        if: |
          inputs.command == 'apply'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        uses: 'abcxyz/guardian/.github/actions/admin@6eb9ac6fb34ceee0c28f4f9aa52d890dbfbb6c4f' # ratchet:abcxyz/guardian/.github/actions/admin@main
        with:
          require_admin: 'false'
          command: 'apply -input=false -auto-approve -lock-timeout=10m'
          terraform_init: 'true'
          working_directory: '${{ matrix.working_directory }}'
          terraform_version: 'REPLACE_TERRAFORM_VERSION'
          protect_lockfile: true
