name: 'guardian_plan'
run-name: 'Guardian Plan - PR #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
    branches:
      - 'main'
    paths:
      - 'test/**'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  plan:
    uses: 'abcxyz/guardian/.github/workflows/plan.yml@main' # ratchet:exclude
    with:
      wif_provider: '${{ vars.GUARDIAN_WIF_PROVIDER}}'
      wif_service_account: '${{ vars.GUARDIAN_WIF_SERVICE_ACCOUNT }}'
      guardian_bucket_name: '${{ vars.GUARDIAN_BUCKET_NAME }}'

      # Optional: only needed if a specific terraform version is required
      # guardian_terraform_version: '1.3.8'

    # Optional: GitHub token if needed using terraform github provider a custom PAT may be required depending on your use case
    # secrets:
    #   gh_token: '${{ secrets.GITHUB_TOKEN }}'
