# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'guardian_apply'
run-name: 'Guardian Apply - PR #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  apply:
    # guardian apply should only be run for merged pull requests
    # pull_requests is required as the pull request number is a unique id for
    # generating cloud storage directory paths for storing plan files
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged }}
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          - 'directory-1'
          - 'directory-2'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3

      # required to download terraform plan files from google cloud storage
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: 'YOUR_GUARDIAN_WIF_PROVIDER' # this can be provided via repository variables
          service_account: 'YOUR_GUARDIAN_WIF_SERVICE_ACCOUNT' # this can be provided via repository variables

      # Optional: set git config auth credentials for private modules if needed
      # - name: 'Git Config'
      #   run: |-
      #     git config --global url."https://guardian-bot:${{ secrets.PAT_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: 'Guardian Apply'
        uses: 'abcxyz/guardian/.github/actions/apply@SHA' # TODO: pin this to the latest sha in the guardian repo

        # Optional: provide environment secrets for terraform providers
        # env:
        #   GITHUB_TOKEN: '${{ secrets.PAT_TOKEN }}'
        #   GITHUB_OWNER: 'YOUR_ORG'

        with:
          working_directory: '${{ matrix.working_directory }}'
          bucket_name: 'YOUR_GUARDIAN_BUCKET_NAME' # this can be provided via repository variables
          terraform_version: '1.3.6'

          # Optional:
          # protect_lockfile: true # default true
          # lock_timeout: '10m'    # default 10m
          # max_retries: '5'       # default 5
          # base_retry_delay: '2'  # default 2s
          # max_retry_delay: '60'  # default 60s
