# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Guardian Plan'
description: |-
  Use this action to run a Terraform Plan process for pull requests.

inputs:
  working_directory:
    description: 'The working directory for Guardian to execute commands in.'
    required: false
    default: '.'
  bucket_name:
    description: 'The Google Cloud Storage bucket name to store Guardian plan files (e.g. my-guardian-state-bucket).'
    required: true
  terraform_version:
    description: 'The Terraform version for Guardian to use.'
    required: true
  protect_lockfile:
    description: 'Prevent modification of the Terraform lockfile.'
    required: false
    default: 'true'
  lock_timeout:
    description: 'The duration Terraform should wait to obtain a lock when running commands that modify state.'
    required: false
    default: '10m'
  max_retries:
    description: 'The maxiumum number of retries when handling failures.'
    required: false
    default: '5'
  max_retry_delay:
    description: 'The max retry delay in seconds when handling failures.'
    required: false
    default: '60'

runs:
  using: 'composite'
  steps:
    - name: 'Bootstrap Out File'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        echo "Unknown error, see logs for details." > "${{ env.OUT_FILENAME }}"

    - name: 'Start Comment'
      id: 'comment'
      uses: 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' # ratchet:actions/github-script@v6
      with:
        github-token: '${{ github.token }}'
        retries: '${{ inputs.max_retries }}'
        script: |-
          const { data: prComment } = await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `**\`🔱 Guardian 🔱\`** - 🟨 **\`PLAN\`** Running for dir: \`${{inputs.working_directory}}\` [[logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }})]`,
          });
          return prComment.id;

    - name: 'Setup Terraform'
      uses: 'abcxyz/secure-setup-terraform@78e3f2fdfb7ebf59ce42141f6dd93bdd65bf04ed' # ratchet:abcxyz/secure-setup-terraform@v0.2.5
      with:
        terraform_version: '${{ inputs.terraform_version }}'
        terraform_module_location: './${{ inputs.working_directory }}'
        terraform_lockfile_location: './${{ inputs.working_directory }}'
        protect_lockfile: '${{ inputs.protect_lockfile }}'
        terraform_wrapper: false

    - name: 'Terraform Format'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        TF_IN_AUTOMATION: 'true' # tell terraform this is an automated workflow https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
      run: |-
        echo "# Terraform Format" > ${{ env.OUT_FILENAME }}
        terraform fmt -check -diff -recursive 2>&1 | tee -a ${{ env.OUT_FILENAME }}

    - name: 'Terraform Init'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        TF_IN_AUTOMATION: 'true' # tell terraform this is an automated workflow https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
      run: |-
        echo "# Terraform Init" > ${{ env.OUT_FILENAME }}
        terraform init -input=false -no-color 2>&1 | tee -a ${{ env.OUT_FILENAME }}

    - name: 'Terraform Validate'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        TF_IN_AUTOMATION: 'true' # tell terraform this is an automated workflow https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
      run: |-
        echo "# Terraform Validate" > ${{ env.OUT_FILENAME }}
        terraform validate -no-color 2>&1 | tee -a ${{ env.OUT_FILENAME }}

    - name: 'Terraform Plan'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        TF_IN_AUTOMATION: 'true' # tell terraform this is an automated workflow https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
      run: |-
        echo "# Terraform Plan" > ${{ env.OUT_FILENAME }}
        terraform plan -lock-timeout=${{ inputs.lock_timeout }} -input=false -no-color -out=tfplan.binary 2>&1 | tee -a ${{ env.OUT_FILENAME }}

    - name: 'Terraform Show'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        TF_IN_AUTOMATION: 'true' # tell terraform this is an automated workflow https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#controlling-terraform-output-in-automation
      run: |-
        echo "# Terraform Show" > ${{ env.OUT_FILENAME }}
        terraform show -no-color tfplan.binary 2>&1 | tee -a ${{ env.OUT_FILENAME }}

    - name: 'GitHub Format'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        sed -i -E 's|^([[:space:]]*)([~])|\1\!|g' ${{ env.OUT_FILENAME }}
        sed -i -E 's|^([[:space:]]*)([-+\!])|\2\1|g' ${{ env.OUT_FILENAME }}

    - name: 'Create Success File'
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        SUCCESS_FILENAME: 'success_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        cp ${{ env.OUT_FILENAME }} ${{ env.SUCCESS_FILENAME }}

    - name: 'Setup Node'
      uses: 'actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c' # ratchet:actions/setup-node@v3
      with:
        node-version: '16'

    - name: 'Install Google Cloud Storage SDK'
      shell: 'bash'
      run: |-
        npm install @google-cloud/storage@~6.9.5

    - name: 'Upload Plan File'
      uses: 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' # ratchet:actions/github-script@v6
      env:
        OUT_FILEPATH: '${{ inputs.working_directory }}/out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
        GUARDIAN_PLAN_PREFIX: 'guardian-plans/${{ github.repository }}/${{ github.event.pull_request.number }}/${{ inputs.working_directory }}'
      with:
        script: |-
          const fs = require("fs");
          const { EOL } = require("os");

          try {
            const { Storage, IdempotencyStrategy } = require("@google-cloud/storage");
            const bucketName = "${{inputs.bucket_name}}";
            const fileName = "${{inputs.working_directory }}/tfplan.binary";
            const destFileName = "${{env.GUARDIAN_PLAN_PREFIX }}/tfplan.binary";

            const storage = new Storage({
              retryOptions: {
                autoRetry: true,
                retryDelayMultiplier: 3,
                totalTimeout: 500,
                maxRetryDelay: "${{inputs.max_retry_delay}}",
                maxRetries: "${{inputs.max_retries}}",
                idempotencyStrategy: IdempotencyStrategy.RetryAlways,
              },
            });

            await storage
              .bucket(bucketName)
              .upload(fileName, { destination: destFileName });
          } catch (err) {
            const errString = JSON.stringify(err, undefined, 2);
            const errorData = `# Upload Plan File${EOL}Error: ${errString}`;

            fs.writeFileSync("${{ env.OUT_FILEPATH }}", errorData, { encoding: "utf8" });

            core.error("Failed to upload plan file");
            core.error(errString);
            core.setFailed("Failed to upload plan file");
          }

    - name: 'Ensure Outfile'
      if: ${{ failure() }}
      shell: 'bash'
      working-directory: '${{ inputs.working_directory }}'
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      run: |-
        touch ${{ env.OUT_FILENAME }}

    - name: 'Failure Comment'
      if: ${{ failure() }}
      uses: 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' # ratchet:actions/github-script@v6
      env:
        OUT_FILENAME: 'out_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      with:
        github-token: '${{ github.token }}'
        retries: '${{ inputs.max_retries }}'
        script: |-
          const fs = require('fs')
          const msg = fs.readFileSync('${{ inputs.working_directory }}/${{ env.OUT_FILENAME }}', { encoding: 'utf8' });

          await github.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: '${{ steps.comment.outputs.result }}',
            body: `**\`🔱 Guardian 🔱\`** - 🟥 **\`PLAN\`** Failed for dir: \`${{inputs.working_directory}}\` [[logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }})]\n
          <details>
          <summary>Details</summary>\n
          \`\`\`diff\n
          ${msg}
          \`\`\`
          </details>`,
          });

    - name: 'Success Comment'
      if: ${{ success() }}
      uses: 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' # ratchet:actions/github-script@v6
      env:
        SUCCESS_FILENAME: 'success_${{ github.run_id }}_${{ github.run_attempt }}.txt'
      with:
        github-token: '${{ github.token }}'
        retries: '${{ inputs.max_retries }}'
        script: |-
          const fs = require('fs')
          const msg = fs.readFileSync('${{ inputs.working_directory }}/${{ env.SUCCESS_FILENAME }}', { encoding: 'utf8' })

          await github.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: '${{ steps.comment.outputs.result }}',
            body: `**\`🔱 Guardian 🔱\`** - 🟩 **\`PLAN\`** Successful for dir: \`${{inputs.working_directory}}\` [[logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }})]\n
          <details>
          <summary>Diff</summary>\n
          \`\`\`diff\n
          ${msg}
          \`\`\`
          </details>`,
          });
