# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Guardian fix is used to run Terraform commands that are most often used
# to fix state after a failed workflow or get outputs for a given module
# directory. Any user with write permissions on the repo can run this workflow.
name: 'guardian_run'
run-name: 'guardian_run - [${{ inputs.command }}] [${{ inputs.entrypoint }}]'

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'COMMAND - The Terraform command to run.'
        required: true
        type: 'choice'
        default: 'plan'
        options:
          - 'plan'
          - 'apply'
          - 'output'
      entrypoint:
        description: 'ENTRYPOINT - A directory to find all child directories containing Terraform configurations. If left blank, the Terraform command will run for all configured directories.'
        default: 'REPLACE_TERRAFORM_DIRECTORY'
        type: 'string'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'

# only one fix  should run at a time
concurrency:
  group: '${{ github.workflow }}'

env:
  GUARDIAN_VERSION: 'REPLACE_GUARDIAN_VERSION'
  GUARDIAN_WIF_PROVIDER: 'REPLACE_GUARDIAN_WIF_PROVIDER'
  GUARDIAN_WIF_SERVICE_ACCOUNT: 'REPLACE_GUARDIAN_WIF_SERVICE_ACCOUNT'
  GUARDIAN_TERRAFORM_VERSION: 'REPLACE_TERRAFORM_VERSION'

jobs:
  init:
    runs-on: 'ubuntu-latest'
    outputs:
      directories: '${{ steps.dirs.outputs.directories }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4

      - name: 'Setup Guardian'
        uses: 'abcxyz/pkg/.github/actions/setup-binary@3eaafa17e8e4b078507bed004ad5c57627d0e486' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
        with:
          download_url: 'https://github.com/abcxyz/guardian/releases/download/v${{ env.GUARDIAN_VERSION }}/guardian_${{ env.GUARDIAN_VERSION }}_linux_amd64.tar.gz'
          install_path: '${{ runner.temp }}/.guardian'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_guardian_${{ env.GUARDIAN_VERSION }}'
          add_to_path: true

      - name: 'Guardian Directories'
        id: 'dirs'
        shell: 'bash'
        env:
          ENTRYPOINT: '${{ inputs.entrypoint }}'
        run: |-
          DIRECTORIES=$(guardian entrypoints -format=json "${ENTRYPOINT}")
          echo "entrypoints -> ${DIRECTORIES}"
          echo "directories=${DIRECTORIES}" >> $GITHUB_OUTPUT

  run:
    if: |
      needs.init.outputs.directories != '[]'
    needs:
      - 'init'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        working_directory: '${{ fromJSON(needs.init.outputs.directories) }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@5a50e581162a13f4baa8916d01180d2acbc04363' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.GUARDIAN_WIF_PROVIDER}}'
          service_account: '${{ env.GUARDIAN_WIF_SERVICE_ACCOUNT }}'

      - name: 'Setup Terraform'
        uses: 'abcxyz/secure-setup-terraform@4d361110d3718e05b118be20051ba2855a2cc9e1' # ratchet:abcxyz/secure-setup-terraform@main
        with:
          terraform_version: '${{ env.GUARDIAN_TERRAFORM_VERSION }}'
          terraform_module_location: './${{ matrix.working_directory }}'
          terraform_lockfile_location: './${{ matrix.working_directory }}'
          protect_lockfile: true
          terraform_wrapper: false

      - name: 'Setup Guardian'
        uses: 'abcxyz/pkg/.github/actions/setup-binary@3eaafa17e8e4b078507bed004ad5c57627d0e486' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
        with:
          download_url: 'https://github.com/abcxyz/guardian/releases/download/v${{ env.GUARDIAN_VERSION }}/guardian_${{ env.GUARDIAN_VERSION }}_linux_amd64.tar.gz'
          install_path: '${{ runner.temp }}/.guardian'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_guardian_${{ env.GUARDIAN_VERSION }}'
          add_to_path: true

      - name: 'Guardian Output'
        if: |
          inputs.command == 'output'
        env:
          DIRECTORY: '${{ matrix.working_directory }}'
        shell: 'bash'
        run: |-
          guardian run -terraform-command="output" "${DIRECTORY}"

      - name: 'Guardian Plan'
        if: |
          inputs.command == 'plan'
        env:
          DIRECTORY: '${{ matrix.working_directory }}'
        shell: 'bash'
        run: |-
          guardian run -terraform-command="plan" -terraform-args="-input=false" "${DIRECTORY}"

      - name: 'Guardian Apply'
        if: |
          inputs.command == 'apply'
        env:
          DIRECTORY: '${{ matrix.working_directory }}'
        shell: 'bash'
        run: |-
          guardian run -terraform-command="apply" -terraform-args="-input=false,-auto-approve" "${DIRECTORY}"
