name: 'Guardian Plan - Test'
run-name: 'Guardian Plan - PR #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  plan:
    uses: './.github/workflows/plan.yml' # ratchet:exclude
    with:
      wif_provider: '${{ vars.GUARDIAN_WIF_PROVIDER}}'
      wif_service_account: '${{ vars.GUARDIAN_WIF_SERVICE_ACCOUNT }}'
      guardian_bucket_name: '${{ vars.GUARDIAN_BUCKET_NAME }}'
