name: 'Warden Apply - Test'
run-name: 'Warden Apply - PR #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'
    paths:
      - 'test/**'

jobs:
  apply:
    uses: 'abcxyz/warden/.github/workflows/warden-apply.yml@main'
    with:
      wif_provider: 'projects/200062081032/locations/global/workloadIdentityPools/github-pool/providers/github-provider-abcxyz-warden'
      wif_service_account: 'warden-ci-sa@verbanicm-dev.iam.gserviceaccount.com'
      warden_bucket_name: 'verbanicm-dev-terraform'
      warden_tf_version: '1.1.8'
