name: 'Guardian Admin - Test'
run-name: 'Guardian Admin ${{ inputs.workspace }} ${{ inputs.number }}'

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'COMMAND - The Terraform command to run including any arguments (this value is appended to the terraform command).'
        required: true
      workspace:
        description: 'WORKSPACE - The Terraform workspace directory to execute the command in. If left blank, the command will run for all paths in .guardian'
      number:
        description: 'PR NUMBER - The Pull Request number to run the actions for (if blank, this runs for main).'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'

jobs:
  admin:
    uses: 'abcxyz/warden/.github/workflows/admin.yml@main' # ratchet:exclude
    with:
      command: '${{ inputs.command }}'
      workspace: '${{ inputs.workspace }}'
      number: '${{ inputs.number }}'
      wif_provider: 'projects/200062081032/locations/global/workloadIdentityPools/github-pool/providers/github-provider-abcxyz-warden'
      wif_service_account: 'warden-ci-sa@verbanicm-dev.iam.gserviceaccount.com'
      guardian_bucket_name: 'verbanicm-dev-terraform'
      guardian_tf_version: '1.1.8'
