# Workflow for IAM drift detection
# Approach:
#   Run on schedule or manual
#   Execute drift script
#   If drift, create issue

name: 'test_guardian_detect_iam_drift'
on:
  workflow_dispatch:
    inputs:
      organization_id:
        description: 'The ID of the GCP organization to detect IAM drift on.'
        required: true

permissions:
  issues: 'write'   # For creating issues.

jobs:
  # add detect drift job
  create_issue:
    name: 'IAM drift detection'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Guardian repo'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          path: 'guardian'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ vars.GUARDIAN_WIF_PROVIDER }}'
          service_account: '${{ vars.GUARDIAN_WIF_SERVICE_ACCOUNT }}'

      - name: 'Guardian Apply'
        uses: './.github/actions/iam-drift-detection'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          organization_id: '${{ inputs.organization_id }}'


