name: 'Guardian Plan - Test'
run-name: 'Guardian Plan - PR #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
    branches:
      - 'main'
    paths:
      - 'test/**'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  plan:
    uses: 'abcxyz/warden/.github/workflows/plan.yml@main' # ratchet:exclude
    with:
      wif_provider: 'projects/200062081032/locations/global/workloadIdentityPools/github-pool/providers/github-provider-abcxyz-warden'
      wif_service_account: 'warden-ci-sa@verbanicm-dev.iam.gserviceaccount.com'
      guardian_bucket_name: 'verbanicm-dev-terraform'
      guardian_tf_version: '1.1.8'
