name: 'Guardian Admin - Test'
run-name: 'Guardian Admin ${{ inputs.directories }} ${{ inputs.number }}'

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'COMMAND - The Terraform command to run including any arguments (this value is appended to the terraform command).'
        required: true
      directories:
        description: 'DIRECTORIES - The Terraform directories to execute the command in. If left blank, the command will run for all directories in .guardian'
      number:
        description: 'PR NUMBER - The Pull Request number to run the actions for (if blank, this runs for main).'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'

jobs:
  admin:
    uses: './.github/workflows/admin.yml' # ratchet:exclude
    with:
      command: '${{ inputs.command }}'
      directories: '${{ inputs.directories }}'
      number: '${{ inputs.number }}'
      wif_provider: '${{ vars.GUARDIAN_WIF_PROVIDER}}'
      wif_service_account: '${{ vars.GUARDIAN_WIF_SERVICE_ACCOUNT }}'
      guardian_bucket_name: '${{ vars.GUARDIAN_BUCKET_NAME }}'
