# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Guardian Apply - Test'
run-name: 'Guardian Apply - PR #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  plan:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    strategy:
      fail-fast: false
      matrix:
        path:
          - 'terraform/ci'
          - 'terraform/projects'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ vars.GUARDIAN_WIF_PROVIDER}}'
          service_account: '${{ vars.GUARDIAN_WIF_SERVICE_ACCOUNT }}'

      - name: 'Setup Terraform'
        uses: abcxyz/secure-setup-terraform@78e3f2fdfb7ebf59ce42141f6dd93bdd65bf04ed # ratchet:abcxyz/secure-setup-terraform@v0.2.5
        with:
          terraform_version: '1.3.6'
          terraform_module_location: './${{ matrix.path }}'
          protect_lockfile: false
          terraform_wrapper: false

      - name: 'Guardian Apply'
        uses: './.github/actions/guardian-apply'
        env:
          GITHUB_TOKEN: '${{ secrets.github_token }}'
        with:
          working_directory: '${{ matrix.path }}'
          bucket_name: '${{ vars.GUARDIAN_BUCKET_NAME }}'
