name: 'Guardian Apply - Test'

on:
  merge_group:
    types:
      - 'checks_requested'

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  apply:
    uses: './.github/workflows/apply.yml' # ratchet:exclude
    with:
      wif_provider: '${{ vars.GUARDIAN_WIF_PROVIDER}}'
      wif_service_account: '${{ vars.GUARDIAN_WIF_SERVICE_ACCOUNT }}'
      guardian_bucket_name: '${{ vars.GUARDIAN_BUCKET_NAME }}'
